version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/app
      - .tmp:/tmp
    ports:
      - "3000:3000"

    command:  bundle exec rails server -b '0.0.0.0'
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

